#Hugo configuration
title = "slimshady"
baseURL = "https:\/\/slimshady.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true
cookieDomain = "slimshady.com"

[params]
loginId = "1758904"
subfolder = ""
